export default {
    FETCH_START: "FETCH_START",
    FETCH_ERROR: "FETCH_ERROR",
    GET_WEATHER_REPORT: "GET_WEATHER_REPORT",
    GET_WEATHER_DAY: "GET_WEATHER_DAY",
    GET_WEATHER_HOURLY: "GET_WEATHER_HOURLY"
};